@urlServidor = https://proyecto-emociones-backend.onrender.com/api/users/
POST {{urlServidor}}
Content-Type: application/json

{
    "uid": "121212",
    "name": "Pedro",
    "lastName": "Márquez",
    "email": "pedrito@gmail.com",
    "birthdate": "15/09/1999",
    "gender": "male"
}