// Para obtener repuesta de un usuario en concreto
@port = 4000
@urlLocal = http://localhost:{{port}}/api/users/
@urlServidor = https://proyecto-emociones-backend.onrender.com/api/users/
GET {{urlServidor}}121299vnjdfjsjdfscc129238923434dje

